-- GENERATED by generate_dbt_models.py -- do not edit by hand.
-- Row counts per migrated table, as a dbt-native cross-check on
-- the Python reconciliation in audit/validation_report.json.

select 'dept_master' as table_name, count(*) as row_count from {{ ref('stg_dept_master') }}
union all
select 'dx_codes', count(*) from {{ ref('stg_dx_codes') }}
union all
select 'enc_log', count(*) from {{ ref('stg_enc_log') }}
union all
select 'patient_records', count(*) from {{ ref('stg_patient_records') }}
union all
select 'prv_tbl', count(*) from {{ ref('stg_prv_tbl') }}
