-- GENERATED by generate_dbt_models.py -- do not edit by hand.
-- Columns come from audit/transformation_rules.json; re-run the generator after
-- any change to mappings or transformation rules.
select
    encounter_id,
    patient_id,
    provider_id,
    encounter_type_code,
    encounter_datetime,
    bill_amount,
    payment_status_code,
    notes
from {{ source('migrated', 'enc_log') }}
