-- GENERATED by generate_dbt_models.py -- do not edit by hand.
-- Columns come from audit/transformation_rules.json; re-run the generator after
-- any change to mappings or transformation rules.
select
    provider_id,
    provider_name,
    provider_type_code,
    dept_id,
    npi_number
from {{ source('migrated', 'prv_tbl') }}
