-- GENERATED by generate_dbt_models.py -- do not edit by hand.
-- Columns come from audit/transformation_rules.json; re-run the generator after
-- any change to mappings or transformation rules.
select
    dx_id,
    encounter_id,
    diagnosis_code,
    dx_description,
    is_primary_diagnosis
from {{ source('migrated', 'dx_codes') }}
