-- GENERATED by generate_dbt_models.py -- do not edit by hand.
-- Columns come from audit/transformation_rules.json; re-run the generator after
-- any change to mappings or transformation rules.
select
    dept_id,
    department_name,
    dept_location,
    is_active
from {{ source('migrated', 'dept_master') }}
