-- GENERATED by generate_dbt_models.py -- do not edit by hand.
-- Columns come from audit/transformation_rules.json; re-run the generator after
-- any change to mappings or transformation rules.
select
    patient_id,
    patient_status_code,
    first_name,
    last_name,
    date_of_birth,
    sex_code,
    admission_datetime,
    discharge_datetime,
    created_ts,
    updated_at
from {{ source('migrated', 'patient_records') }}
