name: 'legacy_migration_validation'
version: '1.0.0'
config-version: 2

profile: 'legacy_migration_validation'

model-paths: ["models"]

models:
  legacy_migration_validation:
    +materialized: view

